### ISSUE TITLE
Investigate and choose some sort of mailing list

### ISSUE THREAD

**Issue by jhuntwork** [jhuntwork/merelinux#10]
Kind of essential for communications of anyone interested in contributing.

**Comment by subnut** [comment]
I think we shall need to host our own server for that, right?..

**Comment by jhuntwork** [comment]
Possibly. I was going to look around for various options.

**Comment by jhuntwork** [comment]
> Possibly. I was going to look around for various options.

If you come across any good ones, feel free to make a recommendation.

**Comment by jhuntwork** [comment]
As a really low bar to entry, I just enabled Github's 'Discussions' feature on this project. Could start with that and see if it addresses the need before committing to something more involved.

**Comment by jhuntwork** [comment]
Closing this for now, since Discussions might meet the current need. We can always revisit if we find something more is needed.

**Comment by fungilife** [comment]
if you look at skarnet's server and obarun.org they use a common listserv that is tried, kiss, and robust/reliable.  I wouldn't trust MS services here of staying as they are or not getting worse.  Already there are tons of scripts running on github like githubassets (3rd party).

**Comment by fungilife** [comment]
https://skarnet.org/lists/ https://obarun.org/mailman/listinfo

**Comment by subnut** [comment]
@fungilife What backend software does skarnet and obarun use? Do you know it's name? I really was wondering about it for a long time.

**Comment by fungilife** [comment]
Obarun uses mailman (I believe 3 mailman 2 requires systemd on arch) but you can get both PKGBUILDs and give it a try.  Tons of python subdependencies.  

On void (musl compiled sw) 
[-] perl-Email-LocalDelivery-1.200_2      Deliver an email to a list of mailboxes
[-] public-inbox-1.6.1_1                  An 'archives first' approach to mailing lists
[-] mlmmj-1.3.0_1        Mailing List Management Made Joyful

This is if your server will be running on mere   :)

**Comment by jhuntwork** [comment]
Thanks for the suggestions @fungilife. I'll take a look at these.
