### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by jhuntwork** [jhuntwork/merelinux#362]
Eventually, user-friendly installation software may be nice to have, but in the meantime at least document the steps required to install the system.

There are at least three possible paths:

1. From a bootable Mere iso image
2. From a generic 3rd-party Linux system
3. From a raw disk image

**Comment by lufv** [comment]
It is great moment to create wiki to put there documentation like this, either here on GitHub or standalone on merelinux.org

**Comment by lufv** [comment]
> From a generic 3rd-party Linux system

It'd be nice to have two ways to install Mere from other Linux: unpacking rootfs or using pacman -r to install packages to mountpoint. There could be metapackage that would install baselayout, busybox and some other essential packages.

**Comment by jhuntwork** [comment]
Yes, you can basically do that now:

```sh
# Grab pacman
mkdir -p /tmp/pacman
curl -LO http://pkgs.merelinux.org/core/pacman-latest-x86_64.pkg.tar.xz
tar -C /tmp/pacman -xf pacman-latest-x86_64.pkg.tar.xz

# Prepare /mnt/mountpoint
mkdir -p /mnt/mountpoint/var/lib/pacman

# base-layout and busybox are included in the 'base' group, but install those separately
# first so that some pre_ or post_ install hooks for other packages will work
sudo /tmp/pacman/usr/bin/pacman -Sy --config /tmp/pacman/etc/pacman.conf \
    -r /mnt/mountpoint base-layout busybox

# Install the rest of the base group
sudo /tmp/pacman/usr/bin/pacman -Sy --config /tmp/pacman/etc/pacman.conf \
    -r /mnt/mountpoint --needed base
```
